agent:
  actions:
    - UP
    - DOWN
    - LEFT
    - RIGHT
  initial_position: [0, 0]
  properties:
    observation:
      offset: 0.5
      random: None
    transition_model:
      offset: 0.5
      random: None
environment:
  grid_dimensions: [5, 5]
  complexities:
    obstacles:
      positions: random # could be defined list
      number: 4
    cues:
      positions: None # could be defined list
      number: 4
  stochastities:
    tranistions:
      occurrences: random # either random or specify a number for how many times they occur
    observation:
      occurences: random # either random or specify a number for how many times they occur
  terminal_states:
    Goal:
      position: [2, 2]
      value: 1
      name: [GOAL]
    Trap:
      position: [ 2, 2 ]
      value: 1
      name: [ GOAL ]
#      - TOP:]
#        position: [ 1, 5 ]
#        reward: 2
#      - BOTTOM:
#        position: [ 3, 5 ]
#        reward: -4
experiment_parameters:
  global:
    time_steps: 50
    verbose_mode: True
    save_name: "experiment_one"
    gen_model:
      noisy_observation: False
      noisy_transition: False
      noisy_start: True
  RF:
    gamma: 5
  AiF:
    gamma: 32
    alpha: 32
    use_states_info_gain: False
    use_utility: True
    policy_len: 4
    agent_selection: "deterministic" # Either deterministic of stochastic
model_derivation:
  None




