agent:
  actions:
    - UP
    - DOWN
    - LEFT
    - RIGHT
    - STAY
  properties:
    observation_offset: 1 # either a number between 0 and 1, or a random, or none for 0
    transition_offset: 0 # either a number between 0 and 1, or a random, or none for 0
  init_state: null
environment:
  grid_dimensions: [9, 9]
  initial_position: null #(0,0)
  complexities:
    obstacles: [ [0,1], [0,2], [0,3], [0,4], [0,5], [0,6], [0,7], [0,8],
      [1,8], [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8],
      [8,7], [8,6], [8,5], [8,4], [8,3], [8,2], [8,1], [8,0],
      [7,0], [6,0], [5,0], [4,0], [3,0], [2,0], [1,0],
      [1,1], [1,2], [1,3], [1,4], [1,5], [1,6], [1,7],
      [2,7], [3,7], [4,7], [5,7], [6,7],
      [6,6], [6,5], [6,4],
      [5,4], [4,4], [3,4],
      [3,5], [3,6],
      [4,6], [5,6], ] # None
    cues: null #[(1,1), (1, 7), (6, 1), (6, 7)] # could be defined list or None
#      - cue1:
#        location: (1,1)
#        trigger: positive
  terminal_states:
    Goal: [5, 3]
    Trap: null #[2, 4]
experiment_parameters:
  global:
    time_steps: [75, 125, 175]
    test_name: "maze_9_by_9"
    trap: False
    verbosity: False
    gen_model:
      noisy_observation: 0.1
      noisy_transition: 0.1
      noisy_start: True
#    environment:
#      changing_obstacles: False
#      changing_cues: False
  RF:
    gamma: 5
  AiF:
    gamma: [8, 16, 32]
    alpha: [8, 16,32]
    agent_class:
      stochastic_short_policy:
        sampling_mode: "marginal"
        policy_len: 3
        agent_selection: "stochastic"
      stochastic_long_policy:
          sampling_mode: "marginal"
          policy_len: 4
          agent_selection: "stochastic"
      stochastic_long_long_policy:
        sampling_mode: "marginal"
        policy_len: 5
        agent_selection: "stochastic"
    # For things below, not sure if they do much
    use_states_info_gain: True
    use_utility: True
    policy_sep_prior: False # cant be true with use_BMA
    use_BMA: True # cant be true with policy_sep_prior
    use_param_info_gain: True
model_derivation:
  None



